language: node_js

sudo: true

node_js:
  - '8'
  - '10'

branches:
  only:
  - master

cache: yarn

matrix:
  fast_finish: true

install:
  - yarn install

notifications:
  email: false

script:
  - yarn run test
